export type StUuid = string
export type Seed = { seed: string; s: string; f: string; r: Rarity; v: string; t: string; u: StUuid }
export type Gender = "Male" | "Female" | "Other"
export type Color = { hex: string; r: number; g: number; b: number; a: number }
export type IrisShape = "Round" | "Almond" | "Heart" | "Dot" | "Star"
export type Iris = { color: Color; shape: IrisShape }
export type Eye = { color: Color; iris: Iris }
export type Eyes = { left: Eye; light: Eye }
export type HairColor = { gradient: boolean; color1: Color; color2: Color }
export type HairStyle = "Variant1" | "Variant2" | "Variant3"
export type Hair = { color: HairColor; length: number; style: HairStyle }
export type Physical = { race: Race; gender: Gender; age: number; height: number; weight: number; eyes: Eyes; hair: Hair; skin_color: Color }
export type Name = { first: string; middle: string | null; last: string }
export type MaritalStatus = "Single" | "Married" | "Divorced" | "Widowed"
export type Parents = { mother: Seed | null; father: Seed | null }
export type Siblings = { count: number; sibling1: Seed | null; sibling2: Seed | null; sibling3: Seed | null; sibling4: Seed | null; sibling5: Seed | null }
export type Children = { count: number; children1: Seed | null; children2: Seed | null; children3: Seed | null; children4: Seed | null; children5: Seed | null }
export type Relationship = { status: MaritalStatus; parents: Parents; siblings: Siblings; children: Children }
export type Rarity = "Common" | "Rare" | "SuperRare" | "SuperSuperRare" | "UltraRare" | "Epic" | "Legendary" | "Mythic" | "Unique"
export type Race = "Human"
export type Class = "Villager"
export type Metadata = { seed: Seed; name: Name; class: Class; physical: Physical; relationship: Relationship; money: number }